name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dioxus
        uses: taiki-e/install-action@cargo-binstall
        with:
          tool: dioxus-cli

      - name: Build Dioxus site
        run: |
          dx build --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/release/public
          cname: harnesslabs.xyz